from flask_restx import Namespace, fields

class IPDto:
    api = Namespace('ips', description='ip related operations')
    model = api.model('ip', {
        'ip': fields.String(readonly=True, attribute='ip'),
        'status': fields.String(readonly=True, attribute='status')
    })

    ip_classification = api.model('ip_classification', {
        'Flow ID': fields.String(required=True),
        'Src IP': fields.String(required=True),
        'Src Port': fields.Integer(required=True),
        'Dst IP': fields.String(required=True),
        'Dst Port': fields.Integer(required=True),
        'Protocol': fields.Integer(required=True),
        'Timestamp': fields.DateTime(required=True),
        'Flow Duration': fields.Float(required=True),
        'Tot Fwd Pkts': fields.Float(required=True),
        'Tot Bwd Pkts': fields.Float(required=True),
        'TotLen Fwd Pkts': fields.Float(required=True),
        'TotLen Bwd Pkts': fields.Float(required=True),
        'Fwd Pkt Len Max': fields.Float(required=True),
        'Fwd Pkt Len Min': fields.Float(required=True),
        'Fwd Pkt Len Mean': fields.Float(required=True),
        'Fwd Pkt Len Std': fields.Float(required=True),
        'Bwd Pkt Len Max': fields.Float(required=True),
        'Bwd Pkt Len Min': fields.Float(required=True),
        'Bwd Pkt Len Mean': fields.Float(required=True),
        'Bwd Pkt Len Std': fields.Float(required=True),
        'Flow Byts/s': fields.Float(required=True),
        'Flow Pkts/s': fields.Float(required=True),
        'Flow IAT Mean': fields.Float(required=True),
        'Flow IAT Std': fields.Float(required=True),
        'Flow IAT Max': fields.Float(required=True),
        'Flow IAT Min': fields.Float(required=True),
        'Fwd IAT Tot': fields.Float(required=True),
        'Fwd IAT Mean': fields.Float(required=True),
        'Fwd IAT Std': fields.Float(required=True),
        'Fwd IAT Max': fields.Float(required=True),
        'Fwd IAT Min': fields.Float(required=True),
        'Bwd IAT Tot': fields.Float(required=True),
        'Bwd IAT Mean': fields.Float(required=True),
        'Bwd IAT Std': fields.Float(required=True),
        'Bwd IAT Max': fields.Float(required=True),
        'Bwd IAT Min': fields.Float(required=True),
        'Fwd PSH Flags': fields.Integer(required=True),
        'Bwd PSH Flags': fields.Integer(required=True),
        'Fwd URG Flags': fields.Integer(required=True),
        'Bwd URG Flags': fields.Integer(required=True),
        'Fwd Header Len': fields.Integer(required=True),
        'Bwd Header Len': fields.Integer(required=True),
        'Fwd Pkts/s': fields.Float(required=True),
        'Bwd Pkts/s': fields.Float(required=True),
        'Pkt Len Min': fields.Float(required=True),
        'Pkt Len Max': fields.Float(required=True),
        'Pkt Len Mean': fields.Float(required=True),
        'Pkt Len Std': fields.Float(required=True),
        'Pkt Len Var': fields.Float(required=True),
        'FIN Flag Cnt': fields.Integer(required=True),
        'SYN Flag Cnt': fields.Integer(required=True),
        'RST Flag Cnt': fields.Integer(required=True),
        'PSH Flag Cnt': fields.Integer(required=True),
        'ACK Flag Cnt': fields.Integer(required=True),
        'URG Flag Cnt': fields.Integer(required=True),
        'CWE Flag Count': fields.Integer(required=True),
        'ECE Flag Cnt': fields.Integer(required=True),
        'Down/Up Ratio': fields.Float(required=True),
        'Pkt Size Avg': fields.Float(required=True),
        'Fwd Seg Size Avg': fields.Float(required=True),
        'Bwd Seg Size Avg': fields.Float(required=True),
        'Fwd Byts/b Avg': fields.Integer(required=True),
        'Fwd Pkts/b Avg': fields.Integer(required=True),
        'Fwd Blk Rate Avg': fields.Integer(required=True),
        'Bwd Byts/b Avg': fields.Integer(required=True),
        'Bwd Pkts/b Avg': fields.Integer(required=True),
        'Bwd Blk Rate Avg': fields.Integer(required=True),
        'Subflow Fwd Pkts': fields.Integer(required=True),
        'Subflow Fwd Byts': fields.Integer(required=True),
        'Subflow Bwd Pkts': fields.Integer(required=True),
        'Subflow Bwd Byts': fields.Integer(required=True),
        'Init Fwd Win Byts': fields.Integer(required=True),
        'Init Bwd Win Byts': fields.Integer(required=True),
        'Fwd Act Data Pkts': fields.Integer(required=True),
        'Fwd Seg Size Min': fields.Integer(required=True),
        'Active Mean': fields.Float(required=True),
        'Active Std': fields.Float(required=True),
        'Active Max': fields.Float(required=True),
        'Active Min': fields.Float(required=True),
        'Idle Mean': fields.Float(required=True),
        'Idle Std': fields.Float(required=True),
        'Idle Max': fields.Float(required=True),
        'Idle Min': fields.Float(required=True)
    })